projects:
  app:
    schemPath: schema/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:6969/api/graphql
  prisma:
    schemaPath: schema/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
